---
title: "Swiss summer temperature distribution"
author: "Duc-Quang Nguyen"
date: " 2018"
output: 
  html_document:
    code_folding: show
    echo: TRUE
    warning: FALSE
    message: FALSE
    toc: yes
    toc_depth: 3
    theme: simplex
---

```{r setup, include=FALSE}
cleanOutput <- F

require(lintr)
library(tidyverse)
library(magrittr)
library(stringr)
library(knitr)
library(skimr)
library(tamMap)
library(swiTheme)

### Getting data in packages
library(rvest)
library(readxl)

### Interactive 
library(htmltools)
library(swiRcharts)
library(rCharts)
library(highcharter)

### Mapping 
# require(rgdal)
# require(rgeos)
# require(maptools)

### Misc stuff
#require(classInt)
#require(viridis)
```

```{r data load}

input.url <- 'http://www.meteosuisse.admin.ch/product/input/climate-data/swissmean/10.18751-Climate-Timeseries-CHTM-1.0-swiss.txt'
rawData.file <- paste0("data/", basename(input.url))
download.file(input.url, rawData.file)  

# Read each txt file and save it as CSV
header <- read.table(rawData.file, skip = 13, stringsAsFactors = FALSE, nrows = 1) %>% unlist(use.names = F)
table <- read.table(rawData.file, skip = 14, stringsAsFactors = FALSE)
colnames(table) <- header

# skim(table)

```

```{r explore}
# take only summer months: april-sep
stemp <- table %>% select(time, apr, may, jun, jul, aug, sep)
# make it long
stemp %<>% gather(month, value, -time)

ggplot(data = stemp %>% filter(time <= 1964)) +
  geom_histogram(aes(x = value))

ggplot(data = stemp %>% filter(time > 1964)) +
  geom_histogram(aes(x = value))

stemp2 <- table %>% select(time, summer)
ggplot(data = stemp2 %>% filter(time <= 1964)) +
  geom_histogram(aes(summer,  ..density..))


ggplot(data = stemp2 %>% filter(time > 1964)) +
  geom_histogram(aes(x = summer,  ..density..))

```

```{r move production graphics}
if (cleanOutput) {
  files <- c("basename_.*html", "js")

  if (!dir.exists("output/bak")) {
    dir.create("output/bak")
  } else {
    list.files("output/bak/", full.names = T, recursive = T) %>% file.remove()
  }
  ori.files <- list.files("output", full.names = T)[list.files("output") != "bak"]
  file.copy(ori.files, to = "output/bak/", recursive = T)
  unlink(ori.files, recursive = T)

  files_tomove <- lapply(files, function(x) list.files(pattern = x)) %>% unlist()
  file.copy(files_tomove, "output", recursive = T)
  unlink(files_tomove, recursive = T)
}
```

```{r linting}
lintr::lint(knitr::current_input())
```
